### ISSUE TITLE
CentOS7.4 update to RHEL7.4？

### ISSUE THREAD

**Issue by zhentianzhang** [oamg/convert2rhel#1037]
How to upgrade centos7.4 to rhel7.4 if the system is not upgraded？

**Comment by bocekm** [comment]
@zhentianzhang, you cannot use convert2rhel for that. We develop and test the tool for a conversion from CentOS Linux 7.9 only. That is the only active and maintained minor version of CentOS Linux 7.

Moreover, landing on RHEL 7.4 is not a good move because that minor version is:
- unmaintained - that implies having unpatched security vulnerabilities
- unsupported by Red Hat so when opening a customer case with Red Hat you'd be advised to update to the supported version of RHEL 7 which is 7.9
