### ISSUE TITLE
[2.0.0]  option --no-rpm-va is irgnored

### ISSUE THREAD

**Issue by mdc-webdb** [oamg/convert2rhel#1268]
Call:
`convert2rhel analyze --no-rpm-va`
result in:

> Running the 'rpm -Va' command which can take several minutes. It can be disabled by using the --no-rpm-va option.
> [2024-06-19T06:38:09+0000] DEBUG - Calling command 'rpm -Va'
> The 'rpm -Va' output has been stored in the /var/log/convert2rhel/rpm_va.log file.
>

**Comment by hosekadam** [comment]
Hello! Thanks for reaching us!

The `--no-rpm-va` requires setting the `CONVERT2RHEL_INCOMPLETE_ROLLBACK` environment variable since version [1.6.0](https://github.com/oamg/convert2rhel/releases/tag/v1.6.0), where the output of the command is needed for complete backup (backup of changed RPM files).

If the `CONVERT2RHEL_INCOMPLETE_ROLLBACK` is not set, the `--no-rpm-va` is ignored - this fact is also mentioned in the log (before the EULA). I understand you could miss the information, I will discuss with the team if we should move the warning somewhere after the EULA to be more visible.

**Comment by mdc-webdb** [comment]
This will be a good idea. Or output an warning, that the option is ignored, during the missing environment variable.

**Comment by hosekadam** [comment]
The warning is printed (`WARNING - We will proceed with ignoring the --no-rpm-va option as running rpm -Va in the analysis mode is essential for a complete rollback to the original system state at the end of the analysis.`), but before the EULA (after printing the used command), which is a big piece of text, it fills your screen and makes the warning invisible.

**Comment by r0x0d** [comment]
> The warning is printed (`WARNING - We will proceed with ignoring the --no-rpm-va option as running rpm -Va in the analysis mode is essential for a complete rollback to the original system state at the end of the analysis.`), but before the EULA (after printing the used command), which is a big piece of text, it fills your screen and makes the warning invisible.

Maybe we could open an issue to move those warnings to happen after the EULA, or we could experiment some other options as well.
