### ISSUE TITLE
Convert Oracle Linux 6: Failed to install subscription-manager packages. See the above yum output for details.

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/convert2rhel#172]
I am experiencing the issue while converting OL6. Traceback is the following:
https://gist.github.com/ZhukovGreen/bbe9a306d5d3cc536e9dff264358eb14

The conversion was running at #100

**Comment by bocekm** [comment]
This happens when you manually pre-download the subscription-manager pkgs to the `/usr/share/convert2rhel/subscription-manager/`. Because convert2rhel downloads these pkgs now, they are there twice, possibly with different versions.

One could imagine a solution in which we remove everything from that folder at the beginning of the conversion but that would have the negative side effect that we would remove also the katello pkg for Satellite 6 that we tell users to put there if they want to use Satellite (https://www.redhat.com/en/blog/converting-centos-rhel-convert2rhel-and-satellite).
