### ISSUE TITLE
Any similar tool to convert from Ubuntu to RHEL

### ISSUE THREAD

**Issue by vgrme** [oamg/convert2rhel#487]
Any similar tool to convert from Ubuntu to RHEL
I'm looking for some tool that can suggest the libs from RHEL so the ubuntu equivalent can be replaced. Thanks

**Comment by SpyTec** [comment]
Hi! 

There is no tool that converts from Ubuntu. Our tool only converts from RHEL-like distros, as they're all ultimately based off of RHEL. Since similarities on how they work is relatively similar it makes it much more straightforward in doing the conversions. Likewise when it comes to converting from CentOS to Oracle, Rocky, or Alma.

You would find it quite difficult to convert from Ubuntu, but you could try to see how this and other tools function and give it a go but you'll have to spend a lot of time to handle all the differences. It's gonna take less time to spin up a RHEL system and just add whatever you need onto it from Ubuntu.

**Comment by pirat89** [comment]
I will just add that Ubuntu is not RPM based distro which means the package managers will not be able to handle the switch from .dev to .rpm packages - not speaking about different names of packages, etc. So even in case someone deal with this enormous problem, it will require to create mapping of ubuntu packages to rhel packages.

I suggest to not waste an energy on any "automatized"/in-place conversion in this case as there are even more obstacles than in comparison to in-place upgrades between major versions of RHEL. Doing clean new installation is best approach in this case. as well, it could be a good time to create playbook / system roles that define the wanted system so new deployment could be easier.
