### ISSUE TITLE
Backup task ("backup_yum_repos" function in convert2rhel/repo.py) should keep "redhat.repo" when "--keep-rhsm" argument is present

### ISSUE THREAD

**Issue by FerreiraEnzoA** [oamg/convert2rhel#734]
While converting a OEL 7.9 VM, subscribed via Red Hat® Satellite 6.10, with "--kep-rhsm" argument, the repos backup isn't successful. However, backup task ("backup_yum_repos" function in [convert2rhel/repo.py](https://github.com/oamg/convert2rhel/blob/main/convert2rhel/repo.py) should keep "redhat.repo" when "--keep-rhsm" argument is present.

`/usr/bin/convert2rhel --activationkey ***** --org ***** --keep-rhsm --no-rpm-va --debug -y`

> [01/31/2023 16:52:51] TASK - [Prepare: Backup System] *******************************************

> Backing up .repo files from /etc/yum.repos.d/.
> No .repo files backed up.

You can review the convert2rhel.log on this [Support case](https://access.redhat.com/support/cases/#/case/03397730/discussion?attachmentId=a096R00002zlWugQAE) to check the issue.

**Comment by bocekm** [comment]
Hi @FerreiraEnzoA, the --keep-rhsm option only ensures that the installed subscription-manager packages are not replaced. The system is however still being re-registered during the conversion (using the RHSM credentials passed through the CLI options). This is what the convert2rhel man page says about the --keep-rhsm option:

> Keep the already installed Red Hat Subscription Management-related packages. By default, during the conversion, these packages are removed, downloaded from verified sources and re-installed. This option is suitable for environments with no connection to the Internet, or for systems managed by Red Hat Satellite. Warning: The system is being re-registered during the conversion and when the re-registration fails, there's no automated rollback to the original registration.

The /etc/yum.repos.d/redhat.repo file is auto-generated by subscription-manager. The reason convert2rhel does not back it up is that it wouldn't be useful after a rollback because even with the use of the --keep-rhsm option convert2rhel re-registers the system causing the redhat.repo file to be re-generated, effectively invalidating the previous redhat.repo content.

The redhat.repo file is not supposed to be edited manually because the repositories defined in it are accessible only with a corresponding attached subscription (attaching a subscription involves copying a necessary certificate to access the repos).

The redhat.repo backup would not be useful in case of a rollback either because part of the rollback is unregistering the system. So, as I stated above, without a system registration and subscription the repos in redhat.repo are inaccessible.

On a related note, there's a known limitation of convert2rhel which we should document in the [official documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index) - during the rollback we have no way to re-register the system back to the original sub-man registration when --keep-rhsm was used. I'll take care of that.
